<?
function display($input) {
	if(is_object($input)) {
		$input = (array) $input;
	}
	if(is_array($input)) {
		echo '<dl>';
		foreach($input as $key => $value) {
			echo '<dt>' . $key . '</dt>';
			echo '<dd>';
			if(is_array($value) || is_object($value))
				display($value);
			else 
				echo $value;
			echo '</dd>';
		}
		echo '</dl>';
	}
	else {
		echo $input;
	}
}
?>

<? foreach ($this->providers as $provider):?>
	<dl>
		<h3>
			<dt>Provider name</dt>
			<dd><? echo $provider->getName(); ?></dd>
		</h3>
		<dt>Id from provider</dt>
		<dd><?=$provider->getId(); ?></dd>
	<? 
	switch ($provider->getName()) {
		case 'facebook': 
		?>
			<dt>Profile</dt>
			<dd>
				<? 
				$profile = $provider->getApi()->getProfile(); 
				display($profile);
				?>
			</dd>
			<dt>Picture</dt>
			<dd>
				<img src="<?=$provider->getApi()->getPicture(); ?>">
			</dd>
		<? 
		break; 
		case 'twitter': 
		?>
			<dt>Profile</dt>
			<dd>
				<? 
				$profile = $provider->getApi()->getProfile(); 
				display($profile);
				?>
			</dd>
			<dt>Picture</dt>
			<dd>
				<img src="<?=$provider->getApi()->getPicture(); ?>">
			</dd>
		<? 
		break; 
		case 'google': 
		?>
			<dt>Profile</dt>
			<dd>
				<? 
				$profile = $provider->getApi()->getProfile(); 
				display($profile);
				?>
			</dd>
		<? 
		break; 
	}
	?>
	</dl>
<? 
endforeach;
?>